tab1vars <- c(
  "num_region",
  # Clinical characteristics
  "num_age",
  "d_age_cat",
  "num_dmgender",
  "num_dmBmi",
  "d_dmBmi_cat",
  "d_dmHF_history",
  "d_dmHF_cat",
  "d_HFdiagnosis",
  "num_dmEflp",
  "num_dmEtio",
  "num_dmEtio_c1",
  "num_dmHT",
  "num_dmMi",
  "num_dmPci",
  "num_dmCabg",
  "num_dmValve",
  "num_dmDev",
  "d_dmDev_cat",
  "num_dmStroke",
  "d_dmAfib2",
  "d_dmAfib3",
  "num_dmPvd",
  "num_dmVte",
  "d_dmDiab",
  "num_dmHyChol",
  "num_dmCopd",
  "num_dmApn",
  "num_dmHepa",
  "d_dmThy",
  "num_dmDis",
  "num_dmDepr",
  "d_no_noncardiac_comorbs",
  "d_dmSmoking1",
  "d_dmSmoking2",
  # Clinical presentation at hospital admission
  "num_dmBpm",
  "num_dmBp1",
  "num_hsHosPresCli",
  "d_hsHosPresCli",
  "num_hsNyha",
  "num_hsRal",
  "d_X_pulmc_alvoedema",
  "num_hsOed",
  "num_hsHf",
  "num_hsFacAf",
  "num_hsFacBrad",
  "num_hsFacMy",
  "num_hsFacUnh",
  "num_hsFacInf",
  "num_hsFacRen",
  "num_hsFacIat",
  "num_hsFacNonc",
  "num_hsFacVa",
  "num_hsFacAne",
  # Laboratory findings at hospital admission
  "num_hsNt",
  "num_hsBnp",
  "d_either_hsNtBnp",
  "num_hsTrop",
  "num_hsSod",
  "num_hsPot",
  "num_hsCre",
  "d_hsCKDEPI",
  "num_hsBun",
  "num_hsUre",
  "num_hsBili",
  "num_hsCrp",
  "num_hsWbc",
  "num_hsHb",
  # ECG at hospital admission
  "num_dcRyth_c1",
  "d_dcRyth",
  "num_dcLbbb",
  "d_qtcfridericia",
  # Echocardiography
  "num_dcEf",
  "num_dcLvdd",
  "num_dcLvh",
  "d_LAVI",
  "num_dcLadim",
  "num_dcRsp",
  "num_dcAorReg",
  "num_dcMitReg",
  "num_dcTriCus",
  "num_dcRhCath",
  "num_dcRhcPap"
)

tab2vars <- c(
  # In-hospital management
  "num_hsIntr",
  "num_hsNitrat",
  "num_hsProDiu",
  "d_dcCardiov_AF",
  "num_dcCora",
  "num_dcPci",
  # In-hospital outcomes
  "d_days_in_hosp",
  "num_dcVital"
)

# Only for patients alive at discharge
tab3vars <- c(
  "num_dcRal",
  "num_dcOed",
  # Clinical status at discharge
  "d_change_weight",
  "num_dcBpm",
  "d_dcBpm_cat",
  "num_dcBp1",
  "d_dcBp1_cat",
  "num_dcNyha",
  "d_dcNyha_cat",
  "num_dcNt",
  "num_dcBnp",
  "d_either_dcNtBnp",
  "d_change_dcNt",
  "d_change_dcBnp",
  "num_dcSod",
  "d_dcSod_cat",
  "d_change_Sod",
  "num_dcPot",
  "d_change_Pot",
  "num_dcCre",
  "d_change_Cre",
  "d_dcCKDEPI",
  "d_dcCKDEPI_cat",
  "d_change_CKDEPI",
  "num_dcHb",
  "d_dcHb_cat",
  "d_change_Hb",

  # Pharmacotherapy at hospital discharge
  "num_mdDiurd",
  "d_loopDiurd",
  "d_loopDiurddose_eqFurosemide",
  "num_mdALd",
  "d_arb_or_ace_or_arni",
  "num_mdACEd",
  "num_mdACEd_c2",
  "d_ACEdose_eqEnapril",
  "d_ACEdosetarget",
  "num_mdATd",
  "num_mdATd_c2",
  "d_ATdose_eqValsartan",
  "d_ATdosetarget",
  "num_mdARNId",
  "num_mdBBd",
  "num_mdBBd_c2",
  "d_BBdose_eqBisoprolol",
  "d_BBdosetarget",
  "num_mdCcbd",
  "num_mdNitd",
  "num_mdIvabd",
  "num_mdDigod",
  "num_mdAmid",
  "num_mdAntiard",
  "num_mdAntipld",
  "num_mdACd",
  "num_mdStatd"
)

# Only for patients alive at discharge and not lost to follow-up
tab4vars <- c(
  # Pharmacotherapy at 1-year follow-up
  "d_f1Diurh",
  "d_f1f1ALh",
  "d_f1_arb_or_ace_or_arni",
  "d_f1ACEh",
  "d_f1ACEhdose_eqEnapril",
  "d_f1ACEdosetarget",
  "d_f1ATh",
  "d_f1ATdose_eqValsartan",
  "d_f1ATdosetarget",
  "d_f1ARNI",
  "d_f1BBh",
  "d_f1BBdose_eqBisoprolol",
  "d_f1BBdosetarget",
  "d_f1Ccbh",
  "d_f1Nith",
  "d_f1Ivabh",
  "d_f1Digoh",
  # Natriuretic peptides at 1-year follow-up
  "num_f1Nt",
  "num_f1Bnp",
  "d_change_f1Nt",
  "d_change_f1Bnp"
)

tabrasvars <- c(
  "num_mdACEdn",
  "num_mdACEdco",
  "num_mdACEdto",
  "num_mdATdn",
  "num_mdATdco",
  "num_mdATdto",
  "num_mdARNIdn"
)

modvars <- c(
  "d_age_cat",
  "num_dmgender",
  "d_dmBmi_cat",
  "num_dmEtio_c1",
  "d_dmHF_cat",
  "num_dmStroke",
  "d_dmAfib2",
  "num_dmPvd",
  "d_dmDiab",
  "num_dmCopd",
  "num_dmHepa",
  "num_dmDis",
  "num_dmDepr",
  "num_hsFacAf",
  "num_hsFacMy",
  "num_hsFacInf",
  "num_hsFacUnh",
  "num_hsFacRen",
  "num_dcMitReg",
  "num_dcTriCus",
  "num_hsIntr",
  "num_dcPci",
  "d_dcBpm_cat",
  "d_dcBp1_cat",
  "d_dcNyha_cat",
  "d_dcSod_cat",
  "d_dcCKDEPI_cat",
  "d_dcHb_cat",
  "num_mdDiurd",
  "num_mdALd",
  "d_arb_or_ace_or_arni",
  "num_mdBBd"
)
