```{r cifunc, cache=cacheon}

kmfunc <- function(time, event, cr = TRUE, ylab, yadj = rep(0, 3)) {
  levef <- paste0("HF", levels(survdata$d_efgroup))

  if (cr) {
    fit <- cuminc(
      ftime = survdata %>% pull(!!sym(time)),
      fstatus = survdata %>% pull(!!sym(event)),
      cencode = 0,
      group = survdata %>% pull(d_efgroup)
    )
  }

  fitkm <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ d_efgroup")), data = survdata)

  # cox regression
  ## uni
  mod <- coxph(formula(paste0("Surv(", time, ",", event, " == 1) ~ d_efgroup")), data = survdata)
  smod <- summary(mod)

  uni <- c("ref", paste0(
    dF(smod$conf.int[1:2, 1], dig = 1),
    " (", dF(smod$conf.int[1:2, 3], dig = 1),
    "-", dF(smod$conf.int[1:2, 4], dig = 1), "), ",
    dF(smod$coefficients[1:2, 5], dig = 3, p = TRUE)
  ))

  ## adj
  amod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 1) ~ d_efgroup + ",
    paste0(modvars, collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))

  adj <- c("ref", paste0(
    dF(exp(asmod$estimate[1:2]), dig = 1),
    " (", dF(exp(asmod$estimate[1:2] - global_z05 * asmod$std.error[1:2]), dig = 1),
    "-", dF(exp(asmod$estimate[1:2] + global_z05 * asmod$std.error[1:2]), dig = 1), "), ",
    dF(asmod$p.value[1:2], dig = 3, p = TRUE)
  ))

  hr <- data.frame("ef" = levef, Crude = uni, Adjusted = adj)
  colnames(hr) <- c("", "Crude HR (95% CI), p", "Adjusted HR (95% CI), p")

  # c(bottom, left, top, right)
  par(mar = c(7, 5.5, 1, 4) + 0.1)

  if (cr) {
    plot(fit[1:3],
      ylab = ylab,
      col = global_kicols,
      wh = c(1110, 1110),
      xlim = c(0, 12 * 30),
      ylim = c(0, .5),
      xlab = "Months",
      axes = F,
      lwd = 3,
      lty = c(1, 2, 3),
      xaxs = "i", yaxs = "i"
    )
  }

  if (!cr) {
    plot(fitkm,
      fun = "event",
      ylab = ylab,
      col = global_kicols,
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 12 * 30),
      ylim = c(0, .5),
      xlab = "Months",
      axes = F,
      lwd = 3,
      lty = c(1, 2, 3),
      xaxs = "i", yaxs = "i"
    )
  }

  axis(2, seq(0, 0.5, 0.1), seq(0, 50, 10), las = 2)
  axis(1, at = seq(0, 12, 1) * 30, seq(0, 12, 1))

  if (cr) {
    m11 <- timepoints(fit[1:3], 12 * 30)$est
  }
  if (!cr) {
    m11 <- 1 - summary(fitkm, 12 * 30)$surv
  }

  mtext(
    side = 4,
    line = .2,
    at = m11 + yadj,
    levef,
    las = 1
  )

  plotrix::addtable2plot(20, 0.4, hr, bty = "n", display.rownames = FALSE, hlines = F, cex = 1)

  mtext("No. at risk", side = 1, line = 3, at = -75, adj = 0, cex = 1)

  mtext(levef[1], side = 1, line = 4, at = -70, adj = 0, cex = 1)
  mtext(levef[2], side = 1, line = 5, at = -70, adj = 0, cex = 1)
  mtext(levef[3], side = 1, line = 6, at = -70, adj = 0, cex = 1)

  nrisk <- summary(fitkm, seq(0, 12, 2) * 30)$n.risk

  axis(1, at = seq(0, 12, 2) * 30, labels = nrisk[1:7], line = 3, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 12, 2) * 30, labels = nrisk[8:14], line = 4, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 12, 2) * 30, labels = nrisk[15:21], line = 5, tick = FALSE, cex.axis = 1)
}
```

```{r ciacdeath, fig.cap="All-cause death", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_death", event = "out_death",
  cr = FALSE,
  ylab = "All-cause death (%)", yadj = c(+.005, -.005, 0.0)
) # p, mr, r
```

```{r ci1hfhosp, fig.cap="First HF hospitalization", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_hosphf",
  event = "out_hosphf_cr",
  ylab = "First HF hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r ciacdeath1hfhosp, fig.cap="All-cause death or first HF hospitalization", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_hosphf", event = "out_deathhosphf",
  cr = FALSE,
  ylab = "All-cause death/first HF hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r cicvdeath1hfhosp, fig.cap="CV death or first HF hospitalization", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_hosphf", event = "out_deathcvhosphf_cr",
  ylab = "CV death/first HF hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r cinoncvdeath, fig.cap="Non-CV death", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_death", event = "out_deathnoncv_cr",
  ylab = "Non-CV death (%)", yadj = c(+.0015, -.0, -0.005)
) # p, mr, r
```

```{r cinoncvhosp, fig.cap="Non-CV hospitalization", cache=cacheon, dependson="cifunc"}
kmfunc(
  time = "outtime_hospnoncv", event = "out_hospnoncv_cr",
  ylab = "Non-CV hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```
