```{r kmfunc, cache=cacheon}

kmfunc <- function(time, event, ylab, yadj = rep(0, 3)) {
  fit <- survfit(formula(paste0("Surv(", time, ",", event, "== 1) ~ d_efgroup")), data = survdata)

  ## logrank
  sd <- survdiff(formula(paste0("Surv(", time, ",", event, "== 1) ~ d_efgroup")), data = survdata)
  p <- dF(pchisq(sd$chisq, length(sd$n) - 1, lower.tail = FALSE), dig = 3, p = TRUE)
  p[p != "<0.001"] <- paste("=", p)


  # c(bottom, left, top, right)
  par(mar = c(4, 4, 1, 4) + 0.1)
  plot(fit,
    fun = "event",
    ylab = ylab,
    xscale = 30.5,
    yscale = 100,
    col = global_kicols,
    mark.time = FALSE,
    bty = "n",
    xlim = c(0, 12 * 30),
    ylim = c(0, .5),
    xlab = "Months",
    axes = F,
    lwd = 3,
    lty = c(1, 2, 3),
    xaxs = "i", yaxs = "i"
  )

  axis(2, seq(0, 0.5, 0.1), seq(0, 50, 10), las = 2)
  axis(1, at = seq(0, 12, 1) * 30, seq(0, 12, 1))

  m11 <- 1 - summary(fit, 12 * 30)$surv

  mtext(
    side = 4,
    line = .2,
    at = m11 + yadj,
    c("HFpEF", "HFmrEF", "HFrEF"),
    las = 1
  )
  
  text(20, 0.4, paste0("Log-rank p ", p), pos = 4)
}
```

```{r kmacdeath, fig.cap="All-cause death", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_death", event = "out_death",
  ylab = "All-cause death (%)", yadj = c(+.005, -.005, 0.0)
) # p, mr, r
```

```{r km1hfhosp, fig.cap="First HF hospitalization", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_hosphf", event = "out_hosphf",
  ylab = "First HF hospitalisation (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r kmacdeath1hfhosp, fig.cap="All-cause death or first HF hospitalization", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_hosphf", event = "out_deathhosphf",
  ylab = "All-cause death/first HF hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r kmcvdeath1hfhosp, fig.cap="CV death or first HF hospitalization", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_hosphf", event = "out_deathcvhosphf",
  ylab = "CV death/first HF hospitalization (%)", yadj = c(0, 0, 0)
) # p, mr, r
```

```{r kmnoncvdeath, fig.cap="Non-CV death", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_death", event = "out_deathnoncv",
  ylab = "Non-CV death (%)", yadj = c(+.0015, -.0, -0.005)
) # p, mr, r
```

```{r kmnoncvhosp, fig.cap="Non-CV hospitalization", cache=cacheon, dependson="kmfunc"}
kmfunc(
  time = "outtime_hospnoncv", event = "out_hospnoncv",
  ylab = "Non-CV hospitalization (%)", yadj = c(-0.007, 0.007, 0)
) # p, mr, r
```
